version: "3.9"

services:
    dharma:
      build:
        context: .
        dockerfile: Dockerfile
        args:
          VARIANT: 1-bullseye
          USER_NAME: ${user_name}
          USER_EMAIL: ${user_email}
          ID: ${id:-20000}
      command: sleep infinity
      volumes:
          - ../:/dharma:cached
      links:
        - db

    db:
      image: redis:latest
      restart: unless-stopped
      volumes:
        - ../db/data:/var/lib/redis/data