PRAGMA FOREIGN_KEYS = ON;

CREATE TABLE IF NOT EXISTS F_RAID (
  ROUND INTEGER NOT NULL PRIMARY KEY ,
  GAME_ID INTEGER NOT NULL REFERENCES F_GAME(GAME_ID),
  RAIDER_ID INTEGER NOT NULL REFERENCES D_PLAYER(PLAYER_ID),
  EMPTY_RAID INTEGER NOT NULL,
  JUDGE INTEGER NOT NULL,
  SCENARIO_CODE INTEGER NOT NULL REFERENCES D_SCENARIO(SCENARIO_CODE),
  SCORE INTEGER NOT NULL,
  CREATED_AT TEXT NOT NULL DEFAULT (DATETIME('now', 'localtime')),
  EDITED_AT TEXT NOT NULL DEFAULT (DATETIME('now', 'localtime'))
);

CREATE TRIGGER TRIGGER_F_RAID_UPDATED_AT AFTER
  UPDATE ON F_RAID
BEGIN
  UPDATE F_RAID
  SET
    UPDATED_AT = DATETIME(
      'now',
      'localtime'
    )
  WHERE
    ROWID == NEW.ROWID;
END;