PRAGMA FOREIGN_KEYS = ON;

CREATE TABLE IF NOT EXISTS D_PLAYER (
  PLAYER_ID INTEGER NOT NULL PRIMARY KEY,
  GENDER_CODE INTEGER NOT NULL REFERENCES D_GENDER(GENDER_CODE),
  PLAYER_NAME TEXT,
  WEIGHT INTEGER NOT NULL,
  HEIGHT INTEGER NOT NULL,
  ROLE_CODE INTEGER NOT NULL REFERENCES D_ROLE(ROLE_CODE)
);