PRAGMA FOREIGN_KEYS = ON;

CREATE TABLE IF NOT EXISTS F_ANTI (
  ANTI_CODE INTEGER NOT NULL PRIMARY KEY,
  ROUND INTEGER NOT NULL REFERENCES F_RAID(ROUND),
  ANTI_ID INTEGER NOT NULL REFERENCES D_PLAYER(PLAYER_ID),
  SUPER_TACKLE INTEGER NOT NULL,
  ANTI_NUMBER INTEGER NOT NULL,
  CREATED_AT TEXT NOT NULL DEFAULT (DATETIME('now', 'localtime')),
  EDITED_AT TEXT NOT NULL DEFAULT (DATETIME('now', 'localtime'))
);

CREATE TRIGGER TRIGGER_F_ANTI_UPDATED_AT AFTER
  UPDATE ON F_ANTI
BEGIN
  UPDATE F_ANTI
  SET
    UPDATED_AT = DATETIME(
      'now',
      'localtime'
    )
  WHERE
    ROWID == NEW.ROWID;
END;