PRAGMA FOREIGN_KEYS = ON;

CREATE TABLE IF NOT EXISTS F_GAME_UNIT (
  ID INTEGER PRIMARY KEY,
  GAME_ID INTEGER  REFERENCE F_GAME_RESULT(ID),
  ANTI_ID INTEGER REFERENCE D_PLAYER(ID),
  RAIDER_ID INTEGER REFERENCE D_PLAYER(ID),
  ANTI_NUMBER INTEGER,
  EMPTY_RAID INTEGER,
  JUDGE INTEGER,
  SCENARIO_CODE INTEGER REFERENCE D_SCENARIO(CODE),
  SCORE INTEGER,
  CREATED_AT TEXT NOT NULL DEFAULT (DATETIME('now', 'localtime')),
  EDITED_AT TEXT NOT NULL DEFAULT (DATETIME('now', 'localtime'))
);

CREATE TRIGGER TRIGGER_F_GAME_UNIT_UPDATED_AT AFTER
  UPDATE ON F_GAME_UNIT
BEGIN
  UPDATE F_GAME_UNIT
  SET
    UPDATED_AT = DATETIME(
      'now',
      'localtime'
    )
  WHERE
    ROWID == NEW.ROWID;
END;